name = "finance-website"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."

[[build.watch_dir]]
dir = "src"

[[build.watch_dir]]  
dir = "static"

[vars]
# 개발용 환경 변수 (실제 배포시 CloudFlare Pages에서 설정)
VITE_NODE_ENV = "development"

# CloudFlare Pages Functions 설정
[functions]
# API 라우트를 CloudFlare Functions로 처리
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 로컬 개발 서버 설정
[dev]
port = 7150
local_protocol = "http"
upstream_protocol = "https"

# Assets 설정
[site]
bucket = ".svelte-kit/output/client" 