export type StockType = {
  Code: string,
  Symbol: string,
  ISU_CD: string,
  Name: string,
  Market: string,
  Dept: string,
  Close: string,
  ChangeCode: string,
  Changes: any,
  ChagesRatio: any,
  Open: any,
  High: any,
  Low: any,
  Volume: any,
  Amount: any,
  Marcap: any,
  Stocks: any,
  MarketId: string
}